""" Expressions régulières utilisées pour analyser l'input utilisateur et construire les réponses de GrandPy """

HELLO = r"^b(on)?j(ou)?r$|^slt$|^salut(ations?)?$|^yo$|^hi$|^👋$"
OC = r"^o(pen)?c(las{1,2}rooms?)?$"
ADDRESS = r"^ad{1,2}res{1,2}e?$"
KNOW = r"^con{1,2}ai(tre|[ts]?|sai[ts]?)(-tu)?$"
HOW = r"^com{1,2}ent$"
GO = r"^vas?(-tu)?$|^al{1,2}ez(-vous)?$"
AT = r"^[àa]$" # [aA] = dangereux
QUESTION = r"^\?{1,3}\!{0,2}$"
WHAT = r"^quel(le)?$"
TIME = r"^heure$"
WEATHER = r"^temps$"
PLAY = r"^jou(ons|e[zr])$"
HEADS = r"^pile$"
TAILS = r"^face$"